### ISSUE TITLE
Create a Fetcher class for Media Entities with methods UploadMediaAsync and DownloadMediaAsync

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#101]
"MediaEntityBase" class in proxy extensions currently has the methods UploadMediaAsync and DownloadMediaAsync. Ideally data classes must not build http requests instead it must be done by fetcher classes. 

So create a new Fetcher class for media entities which supports media entities related methods  UploadMediaAsync and DownloadMediaAsync.

**Comment by MIchaelMainer** [comment]
I believe this is not applicable to the Graph libraries. This sounds like the deprecated O365 libraries.
