### ISSUE TITLE
What is the purpose of the FileAttachment.ContentLocation property

### ISSUE THREAD

**Issue by jamescro** [Microsoft/Vipr#106]
We have had questions from developers (such as here, on StackOverflow: http://stackoverflow.com/questions/28031435/office-365-send-email-with-attachment-using-outlookservicesclient) about attaching files to emails. It appears that the only way to get a file attachment to work is to convert the file into a  MemoryStream object and set that as the value of the FileAttachment.ContentBytes property.

What is the purpose, then, of the ContentLocation property?

**Comment by v-am** [comment]
This doesn't belong to Vipr project.
