### ISSUE TITLE
Undefined initialism in README

### ISSUE THREAD

**Issue by iambmelt** [Microsoft/Vipr#112]
The README mentions **ODCM** numerous times but doesn't provide any definition of what it stands for.

e.g.
**Vipr.Core.** `Provides the interfaces required for extending Vipr as well as the core Client Library generation logic. It also defines the` **ODCM Object Model** `used to describe service capabilities between Readers and Writers.`

What does it stand for? Can we update the README to include this definition?

**Comment by mattgeim** [comment]
This will not be fixed currently, documentation is sufficient.

**Comment by iambmelt** [comment]
Disagree. What does ODCM stand for? It seems awfully important and awfully specific to _this_ project. If we're going to mention it in READMEs we ought to give enough context such that people can understand what we expect them to read.

![screen shot 2016-03-21 at 11 19 08 am](https://cloud.githubusercontent.com/assets/990063/13929376/1518a87e-ef57-11e5-9565-58efd6df3f13.png)

![screen shot 2016-03-21 at 11 19 22 am](https://cloud.githubusercontent.com/assets/990063/13929380/1f2105be-ef57-11e5-99be-765976238669.png)
