### ISSUE TITLE
Client code generation fails with InvalidOperationException if derived entities are defined before their base entity in metadata document.

### ISSUE THREAD

**Issue by RaviPa** [Microsoft/Vipr#115]
if metadata document contains base and derived entity-types in same sequence as shown below.
(Note that EntityNameAttributeMetadata is defined before its base class EnumAttributeMetadata), in such cases on client code generation fails with an InvalidOperationException.

```<EntityType Name="EntityNameAttributeMetadata" BaseType="mscrm.EnumAttributeMetadata"/>            .                                                                <EntityType Name="EnumAttributeMetadata" BaseType="mscrm.AttributeMetadata">
<Property Name="DefaultFormValue" Type="Edm.Int32"/>
<NavigationProperty Name="OptionSet" Type="mscrm.OptionSetMetadata" Nullable="false" ContainsTarget="true"/>
<NavigationProperty Name="GlobalOptionSet" Type="mscrm.OptionSetMetadata" Nullable="false"/>
</EntityType>```

**Comment by v-am** [comment]
The code fails while generating ODCM model:

	Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.WriteNamespaceDeep	C#
 	Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.WriteNamespaces	C#
 	Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.GenerateOdcmModel	C#
 	Vipr.Reader.OData.v4.OdcmReader.GenerateOdcmModel	C#
 	Vipr.Bootstrapper.MetadataToClientSource	C#
 	Vipr.Bootstrapper.MetadataToClientSource	C#
 	Vipr.Bootstrapper.Start	C#
 	Vipr.Program.Main	C#

The logic in WriteNamespaceDeep does assume that all base entity types are defined before their derived types. If that's not the case, the code might fail when it tries to go up hierarchy tree trying to resolve a property defined in a base class.

This can probably be fixed by making a preliminary pass through all entity types just to establish their hierarchy.

**Comment by mattgeim** [comment]
v-am has a fix and will close out when complete.

**Comment by argium** [comment]
I'm encountered an InvalidOperationException when trying to parse the O365 Exchange API Metadata: https://outlook.office365.com/api/beta/$metadata

Is this the same issue?

Call stack is:

>	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.Capabilities.BooleanCapabilityAnnotationParser.GetNavigationProperties(Microsoft.OData.Edm.Expressions.IEdmRecordExpression recordExpression, Vipr.Core.CodeModel.OdcmClass class) Line 82	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.Capabilities.BooleanCapabilityAnnotationParser.ParseCapabilityAnnotationForEntitySet(Vipr.Core.CodeModel.OdcmProperty odcmEntitySet, Microsoft.OData.Edm.Annotations.IEdmValueAnnotation annotation) Line 53	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.Capabilities.ODataCapabilitiesReader.SetCapabilitiesForEntitySet(Vipr.Core.CodeModel.OdcmProperty odcmEntitySet, Microsoft.OData.Edm.IEdmEntitySet edmEntitySet, Microsoft.OData.Edm.IEdmModel serviceModel, Vipr.Reader.OData.v4.Capabilities.PropertyCapabilitiesCache propertyCapabilitiesCache) Line 57	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.AddVocabularyAnnotations(Vipr.Core.CodeModel.OdcmObject odcmObject, Microsoft.OData.Edm.IEdmVocabularyAnnotatable annotatableEdmEntity) Line 127	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.WriteProperty(Vipr.Core.CodeModel.OdcmClass odcmClass, Microsoft.OData.Edm.IEdmEntitySet entitySet) Line 464	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.WriteNamespaceDeep(Microsoft.OData.Edm.IEdmModel edmModel, string namespace) Line 404	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.WriteNamespaces() Line 145	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.GenerateOdcmModel(System.Collections.Generic.IEnumerable<Vipr.Core.TextFile> serviceMetadata) Line 105	C#
 	Vipr.Reader.OData.v4.dll!Vipr.Reader.OData.v4.OdcmReader.GenerateOdcmModel(System.Collections.Generic.IEnumerable<Vipr.Core.TextFile> serviceMetadata) Line 62	C#
 	Vipr.exe!Vipr.Bootstrapper.MetadataToClientSource(string edmxString) Line 123	C#
 	Vipr.exe!Vipr.Bootstrapper.MetadataToClientSource(string edmxString, string outputDirectoryPath) Line 118	C#

**Comment by v-am** [comment]
It's a different issue: code expects a collection of navigation properties and it's not there.

Should be fixed with my latest pull request.

**Comment by v-am** [comment]
Fixed
