### ISSUE TITLE
Vipr crashes with missing fusion.dll using Mono.

### ISSUE THREAD

**Issue by shiftylogic** [Microsoft/Vipr#116]
This is an issue / bug in Its.Configuration.dll that was fixed back in Nov. 2015 (commit c7ddef9bda2735aa7421f6cd4ad8732e6ca39491). I will submit a pull request to fix the issue as well.

No notable impact from taking the version upgrade. All tests ran same before and after change.

**Comment by mattgeim** [comment]
Pull request merged.
