### ISSUE TITLE
Navigation Properties exposed on Concrete Types should be retrievable.

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/Vipr#24]
\vipr\test\csharpwriterunittests\given_an_odcmclass_entity_navigation_property_collection_forced_to_pascal_case.cs
When_retrieved_through_Concrete_ConcreteInterface_Property_then_request_is_sent_with_original_name

Navigation properties exposed on the Concrete Interface, when not expanded, appear as empty collections or null properties. They instead should use a construct like Nullable which depicts that their value is unknown but can be fetched.

**Comment by MIchaelMainer** [comment]
Not applicable to Graph client libraries.
