### ISSUE TITLE
QueryableSet whereExpression should respect ForceToPascalCase

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/Vipr#26]
When the code writer is configured to rename properties, Pascal Casing for example, users will generate a whereExpression which uses the new names. When passed to .GetPath the selected properties should be replaced by the original model's properties.

**Comment by mattgeim** [comment]
see also issue #27

**Comment by MIchaelMainer** [comment]
Unlikely applicable to the new client libraries.
