### ISSUE TITLE
ReadOnlyQueryableSetBase navigationPropertyAccessor should respect ForceToPascalCase

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/Vipr#27]
When the code writer is configured to rename properties, Pascal Casing for example, users will generate a navigationPropertyAccessor which uses the new names. When passed to .Expand the selected properties should be replaced by the original model's properties.

**Comment by MIchaelMainer** [comment]
Not applicable to Microsoft Graph client libraries.
