### ISSUE TITLE
IOdcmWriter intent and design 

### ISSUE THREAD

**Issue by marcote** [Microsoft/Vipr#38]
Hi there,

We want to implement the newly IOdcmWriter interface, but after reviewing some code, specially in the SourceCodeGenerator, I'm not sure about the intent.
https://github.com/Microsoft/Vipr/blob/master/src/Core/Vipr.Core/IOdcmWriter.cs#L11 

I understand the purpose separating the source (or generated code) from the storage implementation, but I have concerns about using a Dictionary as the placeholder in terms of flexibility. 

In the case of the CSharpWriter, there's only one file involved, but on the T4-based writer (Java and iOS) side we have multiple files generated (75 file if we use the Exchange metadata as example).

In our current implementation, we simply pass the output of the T4 Engine to a IFileWriter implementation: 

https://github.com/MSOpenTech/Vipr/blob/dev/src/CLI/Vipr.CLI/Strategies/BaseTemplateProcessor.cs#L137

Perhaps returning an Action and delegating to the implementor what's the next step required to store the files can be more flexible rather than using a plain data structure as a placeholder.

Is it possible to review the design and intent and consider our scenario? 

Thanks in advance.

**Comment by piotrpMSFT** [comment]
Thanks @marcote 

I agree that the use of a Dictionary as the return value is not ideal and should be revisited. @MrTomWhite raised a similar concern, and we should refine the design to meet all of our needs.

The intent of the dictionary was to represent a path/content structure that could then be written to a storage medium. This medium could be a file system, it could also be some other sort of structured storage [we're not ready to talk about other hosts for Vipr yet... coming soon:)]. My expectation was that this was sufficiently expressive as one can express arbitrary project structures within this data structure:

    new Dictionary<string, string>
    {
        { "foo.csproj", "<csprojcontents>" },
        { "dir1\bar.cs", "using Sys..."},
        { "dir2\dir3\zap.cs", "..."}
    };

I don't have access to the MSOpenTech repo you referenced so the implementation therein is not available to me. I think we can go with an alternate design, perhaps one that handles non-text file contents for example, but we should assume that we are dealing with a relative-path key and a file content value. Feel free to suggest an alternative design here, or I'm happy to have a phone conversation today/tomorrow to discuss.

Thanks!

Piotr

**Comment by piotrpMSFT** [comment]
I'll throw out one alternate design to get us started. Instead of a Dictionary<string, string> we can have an IEnumerable<OutputFile>

    public struct OutputFile
    {
        string RelativePath {get;set;}
        string FileContents {get; set;}
    }

This does a much better job of expressing the intent of the Writer's output, I think.

**Comment by marcote** [comment]
@piotrpMSFT yes, we have something more similar to this approach. In our particular case we iterate through each entity, we apply a transformation using the T4 engine and the Template and we get the output : 

```
        public void ProcessingAction(IEnumerable<OdcmObject> source, Template template)
        {
            foreach (var complexType in source)
            {
                ProcessTemplate(template, complexType);
            }
        }

	    protected virtual void ProcessTemplate(Template template, OdcmObject odcmObject)
        {
            var host = GetCustomHost(template, odcmObject);

            var templateContent = File.ReadAllText(host.TemplateFile);
            var output = Engine.ProcessTemplate(templateContent, host);

            if (host.Errors != null && host.Errors.HasErrors)
            {
                var errors = LogErrors(host, template);
                throw new InvalidOperationException(errors);
            }
            FileWriter.WriteText(template, odcmObject.Name, output);
        }
```

The Template class has some information to tell the FileWriter "-Hey, this is how we need to persist the file"
The FileWriter has a specific implementation depending on the language we choose.

Since we have multiple templates, with multiple outputs, aggregate them into an Enumeration can be tricky with our current approach, but I prefer that option rather than a Dictionary.

Thanks

**Comment by piotrpMSFT** [comment]
Please see PR #41 for a proposed fix.

**Comment by piotrpMSFT** [comment]
@marcote since there hasn't been any further conversation on this topic I'm closing the issue. Please Reopen if we need further discussion :)
