### ISSUE TITLE
iOS code generation - property names are capitalized

### ISSUE THREAD

**Issue by MIchaelMainer** [Microsoft/Vipr#48]
This doesn't conform to iOS conventions. https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/CodingGuidelines.html

I'm assuming the iOS SDK for O365 was generated using this tool.

https://github.com/OfficeDev/Office-365-SDK-for-iOS/blob/master/sdk-objectivec/office365_exchange_sdk/Generated/Models/MSOutlookContact.h

**Comment by piotrpMSFT** [comment]
Thanks for pointing this out, @MIchaelMainer !

@joshgav, can the Objective-C Writer folks take a look?

**Comment by joshgav** [comment]
+@greathansen @marcote

I believe we are currently retaining the capitalization from the service descriptor for Obj-C properties with intent to increase readability. However, we're about to review capitalization practices across APIs and libraries and the Cocoa Guidelines will be helpful.

The templates used for Obj-C generation will also be public soon so you'll be able to suggest changes directly. In the meantime I crosslinked here for tracking: https://github.com/OfficeDev/Office-365-SDK-for-iOS/issues/57

**Comment by piotrpMSFT** [comment]
@joshgav, please close this issue once the iOS repo is public and @MIchaelMainer has access to the true tracking issue.

**Comment by piotrpMSFT** [comment]
@joshgav, can we close the Vipr copy of this issue now?

**Comment by joshgav** [comment]
Yes, I don't have close rights so can you please close?
