### ISSUE TITLE
[Annotations]: Add Description annotations support for enum members

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#50]
Enum members were non-annotatable entities, you could not add description annotations for them. With [this change](https://github.com/OData/odata.net/pull/79/commits) it will be possible to do so. Once OData Client for .net releases the next version on nuget with this change, we have to change OdcmModel and CSharpwriter to support description annotations for Enum members.

**Comment by piotrpMSFT** [comment]
The change to the OData Client did not get integrated... this fix might take a while.

**Comment by v-am** [comment]
Looks like OdcmModel already supports that.

**Comment by mattgeim** [comment]
@v-am will confirm and close.
