### ISSUE TITLE
Consider IEnumerable<TextFile> rather than TextFileCollection in IOdcmWriter interface

### ISSUE THREAD

**Issue by marcote** [Microsoft/Vipr#54]
Hi there,

The current `IOdcmWriter` interface returns a `TextFileCollection` and the implementation of the mentioned class is empty.
If no behavior or implementation will be added into the `TextFileCollection` class, consider returning an `IEnumerable<TextFile> `instead.

The current design forces a call to the  AddRange method when working with IEnumerables just to return a collection. 
https://github.com/Microsoft/Vipr/blob/master/test/CSharpWriterUnitTests/CodeGenTestBase.cs#L112

```
proxySources.AddRange(originalProxySources
            .Select(file => new TextFile(file.RelativePath, internalsHeader + file.Contents)));
```
As you can see, we could use the projection instead, without adding it into the proxySources `TextFileCollection`. 

Thoughts?
Thanks!!

**Comment by piotrpMSFT** [comment]
This type was originally a Dictionary<string, string>. When replacing that primitive with types that were easier to reason about [TextFile, TextFileCollection] we noticed two things:
 1. The return type of GenerateProxy is used in many callsites across the solution
 2. As the first few writers solidified, we expected some churn on the data that was to be returned

To avoid a repeat manual refactoring we therefore decided to introduce the TextFileCollection which we could grow and rename to meet the needs of writers as they matured.

@marcote, your team is the other primary contributor of writers at this time. Do you feel an IEnumerable<TextFile> is sufficient and we should remove the TextFileCollection abstraction? Will you not need non-text files to fully describe Java/Objective-C content?

**Comment by marcote** [comment]
@piotrpMSFT right now we have a proper implementation of the IOdcmWriter interface in our T4TemplateWriter, relying on the Vipr's FileWriter class for write to disk ops and works fine. We don't need (so far) anything extra to generate Java/Objective-C code but if that were the case, we could subclass the TextFile class and add what we need there.

I can create a PR with the refactor if interested. I'm pretty sure the code will be cleaner and worse case scenario, while working in the PR I can discover a blocking issue that prevents the refactor.

**Comment by piotrpMSFT** [comment]
For cleanliness, can you create an abstract base class called OutputFile which has just the relative path, make TextFile a derived class of that one, and make the return value an IEnumerable<OutputFile>? I think that deriving, say, ImageFile from TextFile will be pretty strange...

Thanks @marcote !

**Comment by piotrpMSFT** [comment]
@marcote, can you assign to yourself?

**Comment by marcote** [comment]
@piotrpMSFT I can't assign myself. Otherwise I would do it.

**Comment by marcote** [comment]
Thank you guys!
