### ISSUE TITLE
NotHaveExplicitMethod should not throw when the explicit interface is not implemented by the target type

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/Vipr#69]
[Fact]
-        public void The_Concrete_class_does_not_implement_an_explicit_Expand_method()
-        {
-            ConcreteType.Should()
-                .NotHaveExplicitMethod(FetcherInterface, "Expand", "Because abstract Entities cannot be queried");
-        }

**Comment by MIchaelMainer** [comment]
Not applicable to the Graph client libraries.
