### ISSUE TITLE
[ProxyExtensions.Lite]: Move DownloadMediaAsync and UploadMediaAsync out of MediaEntityBase.

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#70]
In the light-weight version of proxy extensions (Microsoft.OData.ProxyExtensions.Lite) DownloadMediaAsync and UploadMediaAsync methods must be moved from MediaEntityBase to a new fetcher class (example 'MediaEntityFetcher'). So in the generated proxy 'MediaEntityFetcher' must be used to download/upload media instead of using the media entity objects themselves.

This is similar to having the Update/Delete method inside 'RestShallowObjectFetcher' instead of 'EntityBase'.

**Comment by MIchaelMainer** [comment]
Not applicable to the Graph client libraries.
