### ISSUE TITLE
Fetcher classes of abstract entities should have Update/Delete/Execute/Expand methods

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#71]
Given an abstract entity should its fetcher class have the Update/Delete/Execute/Expand methods? Having these methods would allow to iterate through collections of the base type to update/delete the derived types. 

Right now these methods are not generated for such fetchers.

**Comment by MIchaelMainer** [comment]
Not applicable to the Graph client libraries.
