### ISSUE TITLE
SaveChangesAsync must not be a part of the Fetcher classes

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#72]
Calling Fetcher.SaveChangesAsync method not only saves the corresponding entities but the entire model changes that are cached in the client. This can be somewhat misleading.

Consider removing it from the Fetcher class. And developers can use client.Context.SaveChangesAsync directly to save all the cached changes in the model (where 'client' is an entity container object).

**Comment by MIchaelMainer** [comment]
Not applicable to the Graph client libraries.
