### ISSUE TITLE
Fetcher.DeleteAsync must not take the entity type object to be deleted as a parameter.

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#75]
DeleteAsync method (inside a fetcher) takes the entity type object to be deleted as a parameter. This is not required. The fetcher class has the URL path to that entity type. It must be able to just send a DELETE request with that URL.

But right now we take a dependency on OData Client libraries. We call DataServiceContext.DeleteAsync to delete an entity type. But this method requires that entity type object as a parameter to send that DELETE request.

**Comment by MIchaelMainer** [comment]
Not applicable to the Graph client libraries.
