### ISSUE TITLE
[OdataReader]: Functions declared in a namespace different from the binding entity type are ignored when generating the OdcmModel

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#76]
Sample metadata - https://api.onedrive.com/v1.0/$metadata
This metadata has some functions inside namespace "view" bound to entity type - "oneDrive.item". But ODataReader ignores these functions in the generated OdcmModel.

**Comment by v-am** [comment]
The logic in Vipr.Reader.OData.v4.OdcmReader.ReaderDaemon.WriteNamespaceDeep assumes that all functions are defined in the same namespace as entity types they are bound to.

**Comment by mattgeim** [comment]
@v-am will take on this to investigate

**Comment by v-am** [comment]
Fixed
