### ISSUE TITLE
[Annotations]: ODataVocabularyReader does not gracefully fail for unknown annotations.

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#84]
ODataVocabularyReader aggressively throws exceptions whenever it encounters annotations it is  unable to parse.

"ODataVocabularyReader.GetOdcmAnnotations" parses and creates a list of 'OdcmVocabularyAnnotation'. But this list not currently used by the odcmwriters to do anything useful. So I have removed the call to "ODataVocabularyReader.GetOdcmAnnotations" as a workaround (See PR #85 ).

FYI @MrTomWhite

**Comment by MrTomWhite** [comment]
:+1:

**Comment by mattgeim** [comment]
Issue doesn't exist anymore in current code based on removal.
