### ISSUE TITLE
[C#Writer]: Abstract EntityType without Key produces non-compiling c# code

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#86]
For example the below edmx produces non-compiling c# code.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="mscrm" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="crmbaseentity" Abstract="true" />
      <EntityType Name="customerrelationship" BaseType="mscrm.crmbaseentity">
        <Key>
          <PropertyRef Name="customerrelationshipid" />
        </Key>
        <Property Name="customerrelationshipid" Type="Edm.Guid" />        
        </EntityType>
        <EntityContainer Name="System">
        <EntitySet Name="customerrelationships" EntityType="mscrm.customerrelationship"/>
        </EntityContainer>
        </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

The collection class for 'crmbaseentity' uses the Key property to overload the index [] operator. But since the key is missing the generated code looks like below snippet and compilation fails with error - "Indexers must have at least one parameter".

public global::mscrm.IcrmbaseentityFetcher this[] {}

According to [OData CSDL spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406397975) an abstract EntityType may or may not define a Key element.

**Comment by v-am** [comment]
I believe this is an issue in C# code generator. ODCM model has enough information to generate an appropriate code.

**Comment by MIchaelMainer** [comment]
Not applicable to the Graph client libraries generator.
