### ISSUE TITLE
Fix Ugly code formatting in Vipr generated C# proxies 

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#97]
Example:
public enum PatchActionType : int
 
    {
 
        Replace
         = 0
        ,
        Append
         = 1
        ,
        Delete
         = 2
        ,
        Insert
         = 3
        ,
        Prepend
         = 4
        ,
    } 

Would probably look better w/o the extra new lines. Maybe something like this instead:
    public enum PatchActionType : int
    {
        Replace = 0,
        Append = 1,
        Delete = 2,
        Insert = 3,
        Prepend = 4
    } 

A space on the generated class names between the name of the class and its parent may be nice.
SQUO:     public partial class PageLinks:Microsoft.OData.ProxyExtensions.Lite.ComplexTypeBase
PROPOSED:     public partial class PageLinks : Microsoft.OData.ProxyExtensions.Lite.ComplexTypeBase

**Comment by MIchaelMainer** [comment]
This is no longer applicable.
