### ISSUE TITLE
Better exceptions can be thrown by Vipr generated C# proxies

### ISSUE THREAD

**Issue by Sridhar-MS** [Microsoft/Vipr#98]
In a number of the call patterns, for example in CopyToSectionGroupAsync(String) (or any actions/functions), there's a Uri check that is followed by throwing a naked exception: 
            Uri myUri = this.GetUrl();
 
            if (myUri == (Uri) null)
 
             throw new Exception("cannot find entity");
 

Could we throw a better exception than this? The expected catch block I'd have to write to catch and handle this exception would feel silly if I have to catch an Exception and then dispatch on the message.

**Comment by MrTomWhite** [comment]
Thanks for adding these issues Sridhar!!!
😃🎉💥

**Comment by MIchaelMainer** [comment]
This is applicable to deprecated O365 client library.
